name: Deploy to Macair
on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.MAC_AIR_HOST }}
          username: bob
          port: ${{ secrets.MAC_AIR_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /usr/local/bin/docker pull bakpark/bobshome:latest 
            /usr/local/bin/docker stop bobshome-container 
            /usr/local/bin/docker rm bobshome-container 
            /usr/local/bin/docker run --name bobshome-container -d -p 3001:3000 bakpark/bobshome:latest
